spring:
  application:
    name: user-service
  data:
    mongodb:
#      uri: mongodb://127.0.0.1:27017/userdb
      uri: mongodb+srv://altdiwakararya1999_db_user:nTMB76sTzmIUNxOj@cluster0.z1klljr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: diwakar
#    password: diwakar
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #  h2:
    #    console:
    #      enabled: true
    #      settings:
    #        web-allow-others: true
    #  datasource:
    #    url: jdbc:h2:mem:test
    #  jpa:
    #    show-sql: true
    #    hibernate:
    #      ddl-auto: create
    #  logging:
    level:
      root: TRACE        # show warnings and errors for everything
      org.springframework: TRACE
      org.hibernate: TRACE
      org.h2: TRACE
server:
  port: 8082


