spring:
  application:
    name: product-service-dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      root: TRACE        # show warnings and errors for everything
      org.springframework: TRACE
      org.hibernate: TRACE
      org.h2: TRACE
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include:
          refresh

server:
  port: 8081
