spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Diwakar38/app-configuration
          username: ${GIT_USER}
          password: ${TOKEN}
server:
  port: 8888